/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package casa.loma.game;
import java.util.Random;
import java.util.Scanner;
import java.lang.String;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.List;
import java.util.Iterator;

public class CasaLomaGame {

    public static Room[] rooms;
    public static NPCs[] npcs;

    // Task system state
    private static final List<Task> activeTasks = new ArrayList<>();
    private static int nextTaskId = 1;
    private static int writeUps = 0;

    private static int hour = 8;
    private static int minute = 0;
    private static double i = 0.0;

    // Task class for tracking assigned tasks
    private static class Task {
        int id;
        String description;
        int targetRoom;
        int assignedTotalMinutes;
        boolean completed;

        Task(int id, String description, int targetRoom, int assignedTotalMinutes) {
            this.id = id;
            this.description = description;
            this.targetRoom = targetRoom;
            this.assignedTotalMinutes = assignedTotalMinutes;
            this.completed = false;
        }
    }

    private static void initializeRooms() {
        // Create and initialize rooms
        Room ClockIn = new Room("Clock In", "Where you start and end your shift.", 0, new int[]{1, 9});
        Room SecurityHallway = new Room("Security Hallway", "Where security resides.", 1, new int[]{0, 2, 4});
        Room Kitchen = new Room("Kitchen", "Where chefs work.", 2, new int[]{1, 3});
        Room IceRoom = new Room("Ice Room", "Where the servers set up.", 3, new int[]{2, 4});
        Room PeacockAlley = new Room("Peacock Alley", "Hallway connecting various rooms.", 4, new int[]{1, 3, 5, 6, 7});
        Room Conservatory = new Room("Conservatory", "A cool white room filled with plants.", 5, new int[]{4, 6});
        Room Library = new Room("Library", "A room filled with old books.", 6, new int[]{4, 5, 7, 8});
        Room GreatHall = new Room("Great Hall", "The main guest entrance.", 7, new int[]{4, 6, 8, 9});
        Room Terrace = new Room("Terrace", "A large balcony overseeing the gardens.", 8, new int[]{6, 7});
        Room FrontOfCastle = new Room("Front of Castle", "The courtyard at the front.", 9, new int[]{0, 8});

        rooms = new Room[]{ClockIn, SecurityHallway, Kitchen, IceRoom, PeacockAlley, Conservatory, Library, GreatHall, Terrace, FrontOfCastle};
    }

    private static void saveNPCsToDatabase(NPCs[] npcs) {
        String query = "INSERT INTO NPCs (name, loi, randomJobs, randomLines) VALUES (?, ?, ?, ?)";
        try (Connection conn = SQLDatabaseManager.getConnection();
        PreparedStatement pstmt = conn.prepareStatement(query)) {

            for (NPCs npc : npcs) {
                // Combines all jobs and lines into a single string to store
                String allJobs = String.join(", ", npc.getRandomJobs());
                String allLines = String.join(", ", npc.getRandomLines());

                pstmt.setString(1, npc.getName());
                pstmt.setDouble(2, npc.getLoi());
                pstmt.setString(3, allJobs);
                pstmt.setString(4, allLines);
                pstmt.executeUpdate();
            }

            System.out.println("NPCs have been saved to the database successfully.");
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Failed to save NPCs to the database.");
    }
}

    
    // Method to Create and Initialize NPCs
    private static void initializeNPCs(){
        //Instances of NPCs
        NPCs Alejandro = new NPCs("Alejandro"); //Porter Manager
        NPCs Bob = new NPCs("Bob"); //Maintenence Manager 
        NPCs Becky = new NPCs("Becky"); //Guest Service Worker
        NPCs Preet = new NPCs("Preet"); //Security Worker
        npcs = new NPCs[] {Alejandro, Bob, Becky, Preet};

        //Setting Lines and Jobs of each NPC
        Alejandro.setJobs("I need 5 chairs to the library. Yesterday!");
        Alejandro.setJobs("What you standing around for? Get me some water bottles. Leave them in the conservatory!");
        Alejandro.setJobs("Move the gelato cart, Front of castle, please!");
        Bob.setJobs("What bus you wating for? You just standing here! Help us move the fountain!");
        Bob.setJobs("Who are you? Whatever bring me the master keys from security.");
        Bob.setJobs("Here change the lightbulb in the peacock alley. What do you mean not part of your job description?");
        Becky.setJobs("Umm, could you, like, get me a chair please? I need it in the great hall. Thanks sis!");
        Becky.setJobs("Apple watermelon is my favourite flavour and I lost it! Can you find my vape? I dropped it in the ");
        Becky.setJobs("Hey, the umbrella on the terrace flew away and hit a woman. It's giving Diddy. Can you fix it?");
        Preet.setJobs("Brother, can you put high top table by entrance, please brother. Thank you.");
        Preet.setJobs("Hey bro give me one table please. Library, brother.");
        Preet.setJobs("Bro I need help outside. The big pot needs move, brother.");

        Alejandro.setLines("How are you doing, sir!");
        Alejandro.setLines("Move!");
        Alejandro.setLines("¡Mira a este pequeño!");
        Bob.setLines("What bus you wating for? Cuz your just standing there!");
        Bob.setLines("A dollar a day keeps HR away! (Old man laugh)");
        Bob.setLines("Working hard or hardly working?");
        Becky.setLines("oh my gawd have you seen my vape? can I hit urs then? You DON'T have one...");
        Becky.setLines("SZA just dropped an album!!!");
        Becky.setLines("OMG I luv ur pants. its giving will smith in pursuit of happiness");
        Preet.setLines("How you, brotha? I'm good.");
        Preet.setLines("Bro, I have nephew, he need job. You guys hiring? Let me know.");
        Preet.setLines("Hot day today, you guys drink water.");

        //Setting likelyhood of interaction (loi)
        Alejandro.setLoi(0.5);
        Bob.setLoi(0.7);
        Becky.setLoi(0.25);
        Preet.setLoi(0.4);

        // Save NPCs to the database
        //saveNPCsToDatabase(npcs);
        //DatabaseInitializer.initializeDatabase("path/to/initialize_npcs.sql");

    }

    public static NPCs[] getNPCsArray() {
        return npcs;
    }

    private static void startGame(){
        //Initialize Game with Base Variables
        //game over clause boolean gameOver = false; 
        String text = "";
        int roomNum = 0; //clock in
        //clock
        hour = 8;
        minute = 0;

        //User Input
        Scanner sc = new Scanner(System.in);

        System.out.println("Welcome to Casa Loma! You are about to clock in.");
        i = 0.0;
        int num = -1;
        while(i < 8.0){

            if (!sc.hasNextLine()) {
                System.out.println("Input closed. Exiting game.");
                return;   // or break; depending on context
            }
            text = sc.nextLine();
            
            //Checking user's input to see how to respond
            if (text.equalsIgnoreCase("tasks")) {
                printActiveTasks();
                continue;
            }
            if (text.equalsIgnoreCase("complete") || text.equalsIgnoreCase("complete task")) {
                attemptCompleteFirstTask(roomNum);
                continue;
            }
            if(text.length() == 1){ // checks if user input is a room number or passing time or an action
                num = Integer.parseInt(text); //changes player input to int
            }
            //Pass time feature
            if(text.equalsIgnoreCase("pass time")){
                if(minute == 0){
                    minute = 30;
                    i += 0.5;
                    System.out.println("The time is " + hour + ":" + minute);
                }else{
                    minute = 0;
                    hour += 1;
                    i += 0.5;
                    System.out.println("The time is " + hour + ":00");
                }
                // Calls Room Class methods to spawn NPC chances
                rooms[roomNum].spawnNPCs();
                interactWithNPCsInRoom(roomNum);
                checkOverdueTasks(); // check tasks after time passes
                continue;
            }
            //Moving rooms feature
            if (num == roomNum) { //checks if user is already in room
                System.out.println("You are already in this room. Would you like to pass time?");
                continue;

            } else { //checks if user chose a neigbouring room
                boolean isNeighbor = false;
                for (int neighbor : rooms[roomNum].getNeighbor()) {
                    if (num == neighbor) {
                        isNeighbor = true;
                        break;
                    }
                }
            
                if (isNeighbor) { 
                    roomNum = num; // Update the current room number
                    rooms[roomNum].spawnNPCs(); // Spawn NPCs
                    System.out.println("You have moved to the " + rooms[roomNum].getRoomName() + ". Would you like to pass time?");  
                    interactWithNPCsInRoom(roomNum); // Check for NPC interactions
                    continue; 
                } else {
                    System.out.println("You're not beside that room. Look at the legend and the map to navigate to other rooms.");
                    continue;
                }
            }
            //NPC chance for interaction/mission (cannot have interaction + mission in one go)
            /*if(){

            }*/

        }
        
        System.out.println("Bob: Headin' home now? Make sure to come to work at 4:00 AM tomorow!");
        System.out.println("Day off? What that?");
        sc.close();
    }
    
    private static void interactWithNPCsInRoom(int roomNum) {
        Random random = new Random();
         // Room currentRoom = rooms[roomNum];
        double totalLoi = 0.0;

        if (npcs == null || npcs.length == 0) {
            System.out.println("There are no NPCs in this room right now.");
            return;
        }

        for (NPCs npc : npcs) {
            totalLoi += npc.getLoi(); // Calculate total LOI for all room NPCs
        }

        double randomValue = random.nextDouble() * totalLoi; // Random value within the range of total LOI
        double cumulativeLoi = 0.0;

        for (NPCs npc : npcs) {
            cumulativeLoi += npc.getLoi();
            if (randomValue <= cumulativeLoi) {
                // Decide whether the NPC gives a job or a line
                if (random.nextBoolean()) {
                    String job = extractRandomStringFromObject(npc.getRandomJobs());
                    if (job == null || job.trim().isEmpty()) {
                        job = npc.getName() + " asks you to do something.";
                    }
                    int target = parseTargetRoomFromText(job);
                    int assignedTotalMinutes = hour * 60 + minute;
                    Task t = new Task(nextTaskId++, job, target, assignedTotalMinutes);
                    activeTasks.add(t);
                    System.out.println(npc.getName() + " has a task for you: " + job);
                } else {
                    String line = extractRandomStringFromObject(npc.getRandomLines());
                    if (line == null || line.trim().isEmpty()) {
                        line = npc.getName() + " says hello.";
                    }
                    System.out.println(npc.getName() + " says: " + line);
                }
                return; // Exit after interacting with one NPC
            }
        }
    }

    public static void main(String args[]){
        initializeRooms();
        //DatabaseInitializer.initializeDatabase("sql/schema.sql");
        //DatabaseInitializer.initializeDatabase("sql/seed_npcs.sql");
        initializeNPCs();
        startGame();
    }

    private static String extractRandomStringFromObject(Object obj) {
        if (obj == null) return null;
        Random r = new Random();
        try {
            if (obj instanceof String[]) {
                String[] arr = (String[]) obj;
                if (arr.length == 0) return null;
                return arr[r.nextInt(arr.length)];
            } else if (obj instanceof List) {
                List<?> list = (List<?>) obj;
                if (list.isEmpty()) return null;
                Object pick = list.get(r.nextInt(list.size()));
                return (pick == null) ? null : pick.toString();
            } else {
                return obj.toString();
            }
        } catch (Exception e) {
            return obj.toString();
        }
    }

    private static int parseTargetRoomFromText(String text) {
        String lower = text.toLowerCase();
        if (lower.contains("library")) return findRoomByName("Library");
        if (lower.contains("conservatory")) return findRoomByName("Conservatory");
        if (lower.contains("front") && lower.contains("castle")) return findRoomByName("Front of Castle");
        if (lower.contains("great hall") || lower.contains("greathall")) return findRoomByName("Great Hall");
        if (lower.contains("terrace")) return findRoomByName("Terrace");
        if (lower.contains("kitchen")) return findRoomByName("Kitchen");
        if (lower.contains("ice room") || lower.contains("ice")) return findRoomByName("Ice Room");
        if (lower.contains("peacock")) return findRoomByName("Peacock Alley");
        if (lower.contains("security") || lower.contains("security hallway")) return findRoomByName("Security Hallway");
        if (lower.contains("clock in") || lower.contains("clockin")) return findRoomByName("Clock In");
        return 0;
    }

    private static int findRoomByName(String name) {
        for (int i = 0; i < rooms.length; i++) {
            if (rooms[i].getRoomName().equalsIgnoreCase(name)) return i;
        }
        return 0;
    }

    // New: attempt to complete the first (oldest) active task
    private static void attemptCompleteFirstTask(int currentRoom) {
        if (activeTasks.isEmpty()) {
            System.out.println("You have no active tasks.");
            return;
        }
        Task t = activeTasks.get(0);
        if (t.completed) {
            activeTasks.remove(0);
            System.out.println("That task was already completed.");
            return;
        }
        if (t.targetRoom != currentRoom) {
            System.out.println("You're not in the correct room to complete that task. 15 minutes pass as a penalty.");
            advanceTimeByMinutes(15);
            return;
        } else {
            t.completed = true;
            activeTasks.remove(0);
            System.out.println("Task completed: " + t.description + " (Task #" + t.id + ")");
        }
    }

    // New: list active tasks with remaining time and target room
    private static void printActiveTasks() {
        if (activeTasks.isEmpty()) {
            System.out.println("No active tasks.");
            return;
        }
        int nowTotal = hour * 60 + minute;
        System.out.println("Active tasks:");
        for (Task t : activeTasks) {
            int elapsed = nowTotal - t.assignedTotalMinutes;
            int remaining = 60 - elapsed;
            String roomName = rooms[t.targetRoom].getRoomName();
            System.out.printf(" #%d: %s — target: %s — assigned %d min ago — %s\n",
                    t.id, t.description, roomName, elapsed,
                    (remaining > 0 ? ("time left: " + remaining + " min") : "OVERDUE"));
        }
    }

    // New: advance time and update shift/hour counters, then check overdue tasks
    private static void advanceTimeByMinutes(int minutesToAdd) {
        int totalMinutes = hour * 60 + minute + minutesToAdd;
        hour = (totalMinutes / 60) % 24;
        minute = totalMinutes % 60;
        i = (hour - 8) + (minute / 60.0);
        checkOverdueTasks();
    }

    // New: check tasks and issue write-ups for tasks overdue >= 60 minutes
    private static void checkOverdueTasks() {
        int nowTotal = hour * 60 + minute;
        Iterator<Task> it = activeTasks.iterator();
        while (it.hasNext()) {
            Task t = it.next();
            if (!t.completed) {
                int elapsed = nowTotal - t.assignedTotalMinutes;
                if (elapsed >= 60) {
                    it.remove();
                    writeUps++;
                    System.out.println("You were written up for failing to complete a task in time: " + t.description + ". (Write-ups: " + writeUps + "/3)");
                    if (writeUps >= 3) {
                        System.out.println("Three write-ups. You have been fired.");
                        System.exit(0);
                    }
                }
            }
        }
    }

}
