/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 */

sourceSets {
    test {
        kotlin.srcDirs = ['src/test/kotlin']
    }
}


plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.2")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.9.2")

    // Kotlin test library
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Mocking (if needed)
    testImplementation("io.mockk:mockk:1.13.4")
}

application {
    // Define the main class for the application.
    mainClass.set("casa.loma.game.App")
}

tasks.test {
    useJUnitPlatform()
}


tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
